# Generated by Django 5.2.7 on 2025-10-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaComision',
            fields=[
                ('reglaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la regla / meta', max_length=100)),
                ('meta_venta', models.DecimalField(decimal_places=2, help_text='Meta en dinero', max_digits=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 5 para 5%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedorId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaId', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestorventas.vendedor')),
            ],
        ),
    ]
